# hostendpoints.yaml
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: master-ens3
  labels:
    role: node
spec:
  interfaceName: ens3
  node: master
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: worker1-ens3
  labels:
    role: node
spec:
  interfaceName: ens3
  node: worker1
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: worker2-ens3
  labels:
    role: node
spec:
  interfaceName: ens3
  node: worker2
