---
- name: Download the public signing key for the Kubernetes package repositories
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present
    create: yes

- name: Install kubernetes tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Disable apt update of selected packages
  command: apt-mark hold kubelet kubeadm kubectl

- name: Initialize Kubernetes cluster (on master node)
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configure kubectl for root
  become: true
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chown root:root /root/.kube/config

- name: Download Helm Binary
  unarchive:
    remote_src: true
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp

- name: Move Helm Binary
  copy:
    remote_src: true
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: 0755

- name: Extract Kubeconfig to Host machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ../resources/kubeconf.conf
    flat: true
