---
- name: Download the public signing key for the Kubernetes package repositories
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present
    create: yes

- name: Install kubernetes tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Disable apt update of selected packages
  command: apt-mark hold kubelet kubeadm kubectl

- name: Initialize Kubernetes cluster (on master node)
  when: "'master' in group_names"
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configure kubectl for root
  when: "'master' in group_names"
  become: true
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chown root:root /root/.kube/config

- name: Generate Join Command
  when: "'master' in group_names"
  command: kubeadm token create --print-join-command
  register: join_cmd

- name: Create fact on master
  when: "'master' in group_names"
  set_fact:
    join_command: "{{ join_cmd.stdout }}"

- name: Synchronize join_command variable
  when: "'master' in group_names"
  wait_for:
    timeout: 10
  until: hostvars[groups['master'][0]].get('join_command') is defined
  retries: 10
  delay: 5

- name: Join Control Plane
  when: "'worker' in group_names"
  command: "{{ hostvars[groups['master'][0]].join_command }}"


- name: Download Helm Binary
  when: "'master' in group_names"
  unarchive:
    remote_src: true
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp

- name: Move Helm Binary
  when: "'master' in group_names"
  copy:
    remote_src: true
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: 0755

- name: Create .kube
  when: "'master' in group_names"
  file:
    path: /home/ubuntu/.kube/
    state: directory

- name: Move Kubernetes config
  when: "'master' in group_names"
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    mode: 0755
